---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    yum:
      name: httpd
      state: absent
    when:  ansible_distribution_version == "CentOS"

  - name: remove php support for apache
    yum:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"
